---
version: '2'

linters:
    enable:
        # Enabled for all projects
        - asciicheck
        - bidichk
        - bodyclose
        - canonicalheader
        - contextcheck
        - copyloopvar
        - cyclop
        - decorder
        - dogsled
        - dupl
        - dupword
        - durationcheck
        - embeddedstructfieldcheck
        - err113
        - errchkjson
        - errname
        - errorlint
        - exhaustive
        - exhaustruct
        - exptostd
        - fatcontext
        - forbidigo
        - forcetypeassert
        - funcorder
        - funlen
        - ginkgolinter
        - gocheckcompilerdirectives
        - gochecknoglobals
        - gochecknoinits
        - gochecksumtype
        - gocognit
        - goconst
        - gocritic
        - gocyclo
        - godoclint
        - godot
        - goheader
        - gomoddirectives
        - gomodguard
        - goprintffuncname
        - gosec
        - gosmopolitan
        - govet
        - grouper
        - importas
        - ineffassign
        - interfacebloat
        - intrange
        - iotamixing
        - loggercheck
        - maintidx
        - makezero
        - mirror
        - misspell
        - mnd
        - musttag
        - nakedret
        - nestif
        - nilerr
        - nilnesserr
        - nilnil
        - noctx
        - noinlineerr
        - nolintlint
        - nosprintfhostport
        - paralleltest
        - perfsprint
        - prealloc
        - predeclared
        - promlinter
        - protogetter
        - reassign
        - recvcheck
        - rowserrcheck
        - sloglint
        - spancheck
        - sqlclosecheck
        - staticcheck
        - tagalign
        - tagliatelle
        - testableexamples
        - testifylint
        - testpackage
        - thelper
        - tparallel
        - unconvert
        - unparam
        - unqueryvet
        - unused
        - usestdlibvars
        - usetesting
        - wastedassign
        - whitespace
        - zerologlint

        # Enabled for public libraries
        - lll
        - godox
        - revive
